#!/bin/bash
echo "ENABLED_SERVICES=n-cpu,rabbit,g-api,neutron,q-agt
SERVICE_HOST=$1
MYSQL_HOST=\$SERVICE_HOST
RABBIT_HOST=\$SERVICE_HOST
Q_HOST=\$SERVICE_HOST
MATCHMAKER_REDIS_HOST=\$SERVICE_HOST" >> devstack/localrc
