heat_template_version: 2013-05-23

description: >
  Template creating a key pair with a given public key.

parameters:
  name:
    type: string
    description: Name for key pair.

  public_key:
    type: string
    description: The public part of the key pair.

resources:
  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: name }
      public_key: { get_param: public_key }
